<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sasi" failures="1" tests="7" name="Test" time="15.351" errors="0" timestamp="2023-04-16T16:29:31 IST">
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_1" time="0.285"/>
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_2" time="0.233"/>
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_3" time="0.244"/>
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.226">
    <skipped/>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.243">
    <skipped/>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.244">
    <skipped/>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.243">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this servic] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this servic] but found [Epic sadface: Username and password do not match any user in this service]
at TestRunner.Login_Func.login_Scenario_4(Login_Func.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login_Scenario_4 -->
</testsuite> <!-- Test -->
