<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Sasi" failures="1" tests="4" name="Default test(failed)(failed)" time="8.403" errors="0" timestamp="2023-04-16T15:55:29 IST">
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.27">
    <skipped/>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.247">
    <skipped/>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.235">
    <skipped/>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_4" time="0.242">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this servic] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this servic] but found [Epic sadface: Username and password do not match any user in this service]
at TestRunner.Login_Func.login_Scenario_4(Login_Func.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login_Scenario_4 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_1" time="0.0">
    <ignored/>
  </testcase> <!-- login_Scenario_1 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_2" time="0.0">
    <ignored/>
  </testcase> <!-- login_Scenario_2 -->
  <testcase classname="TestRunner.Login_Func" name="login_Scenario_3" time="0.0">
    <ignored/>
  </testcase> <!-- login_Scenario_3 -->
</testsuite> <!-- Default test(failed)(failed) -->
